# 称号buff状态 true 进行清理 false不处理
playerTitleBuff: true
playerTitleBuffOnMsg: "&8[&a✔&8] &7称号buff 恢复"
playerTitleBuffOffMsg: "&8[&a✔&8] &7称号buff 隐藏"

# 玩家种族加成 true 进行清理 false不处理
playerRaceBuff: true
playerRaceBuffOnMsg: "&8[&a✔&8] &7种族之力 恢复"
playerRaceBuffOffMsg: "&8[&a✔&8] &7种族之力 隐藏"

# 玩家公会PVP检查 true 进行关闭 false不处理
playerGuildPvp: true
playerGuildPvpOnMsg: "&8[&a✔&8] &7公会PVP 启用"
playerGuildPvpOffMsg: "&8[&a✔&8] &7公会PVP 禁用"